### PR TITLE
Don't filter out discovered BT peripherals by `isPresent` (Windows)

### LINKED ISSUE #94: After connecting EV3/SPIKE Prime on windows, can't reconnect without first un-pairing
Once I have connected to an EV3, and then disconnected, and then restarted Scratch Link (due to the crash in https://github.com/LLK/scratch-link/issues/93), when I attempt to connect again, the EV3 never appears in the scan.

The only reliable way I have found to be able to find and connect to the EV3 is to use the Windows Bluetooth settings to unpair the EV3 (i.e. "remove this device"). After I do that, the EV3 appears immediately in the scan, and I am able to connect.

Scratch Link 1.1.9.0
Chrome 70
Windows 10 Pro 1803 build 17134.345

### PR DESCRIPTION
**Pull request by evhan55**
### Resolves

- Resolves #94: After connecting EV3/SPIKE Prime on windows, can't reconnect without first un-pairing

### Proposed Changes

Remove the check for `isPresent` on the list of discovered devices, because unfortunately that is set to `false` to devices that are _present but previously paired_. Since we want people to be able to connect to devices that have been previously paired, we need to return them in the list of discovered devices, whether they are within range or not.

### Note

This PR leaves the declaration for the `IsPresentPropertyName` variable name on line 28 for possible future use, but it can be removed, too.

### CODE REVIEW

**Comment by evhan55** [comment]
@cwillisf 

We are looking into issue #94 in preparation for the LEGO SPIKE Prime which also exhibits this bug in addition to the EV3.  I found that by commenting on the filtering of discovered peripherals based on the `isPresent` property, the bug is fixed.  According to documentation, once BT devices are paired on Windows, they enter a cache and `isPresent` is no longer true for them.  So, I think we don't want to filter on that property? The Windows UWP documentation on this stuff is worded in a confusing way, but commenting out what I did does fix the problematic symptom we are seeing.

EDIT:
The documentation for `isPresent` says this confusing thing: 
> Indicates if the device is currently present, meaning the device is live and discovered over the network or wireless protocol. Once a device has been paired with the system, the device is cached. After this, the device will be automatically discovered when querying for AssociationEndpoint objects. Because of this, you cannot rely on just discovering the device with a query to indicate whether or not it is currently usable. That is why this property is important.

**Comment by evhan55** [comment]
@cwillisf 

Another possible way to fix this is to check the `isPaired` property and check the following:

- `isPresent`? if not, `isPaired`?

to prevent getting cached devices.

**Comment by evhan55** [comment]
It seems the previous fix I mention actually always returns all paired devices whether they are present or not, so I have to rethink the strategy, sorry for the false alarm!

**Comment by evhan55** [comment]
Saving these discussions here for reference:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/899f6b6e-19fd-40c5-ba1c-741b60b6cfd8/getting-devicewatcher-updates-when-ble-device-is-not-reachable?forum=wpdevelop

https://tutel.me/c/programming/questions/40950482/search+for+devices+in+range+of+bluetooth+uwp

https://stackoverflow.com/questions/54252953/uwp-how-find-already-paired-devices-but-which-now-in-discoverable-mode

https://stackoverflow.com/questions/40950482/search-for-devices-in-range-of-bluetooth-uwp

File: Windows/scratch-link/BTSession.cs [hunk 1]
```diff
@@ -234,11 +233,6 @@ private async void ListenForMessages()
 
         private void PeripheralDiscovered(DeviceWatcher sender, DeviceInformation deviceInformation)
         {
-            if (!deviceInformation.Properties.TryGetValue(IsPresentPropertyName, out var isPresent)
-                || isPresent == null || (bool)isPresent == false)
```
Comment (cwillisf) [inline Windows/scratch-link/BTSession.cs:238]: I would recommend leaving a comment here to remind us why we don't check `isPresent`... otherwise I can see us reintroducing this bug in a year or two :/

Also, out of curiosity: when a device is paired, is `isPresent` null or is it false?

EDIT: Oh, I see up at the top that you said it's false. Thanks :)

**Review by cwillisf — CHANGES_REQUESTED** [review]
I think it needs a comment but the ~code~ looks great!

File: Windows/scratch-link/BTSession.cs (hunk 1 above)
Comment (evhan55) [reply Windows/scratch-link/BTSession.cs:238]: @cwillisf 

When the device is paired on Windows10 and I try the following:
```
deviceInformation.Properties.TryGetValue(IsPresentPropertyName, out var ispresent);
Debug.Print("ispresent: {0}", ispresent);
```

It prints:
`ispresent: False`

**Comment by evhan55** [comment]
@cwillisf Thanks for the review, I added a comment to try to explain the change.  Please let me know if it's not clear enough and I can try again.

**Review by cwillisf — APPROVED** [review]
The comments are great! Thanks :)

**Comment by evhan55** [comment]
@cwillisf Thanks! I found a small typo in the first comment (extra 'for') so I will fix that and then merge.
